import Head from 'next/head'
import Image from 'next/image'
import { Heading, Link } from '@chakra-ui/layout';
import Hero from './components/Hero';
import Features from './components/Features';
import More from './components/More';
import Things from './components/Things';
import Change from './components/Change';
import Featurestwo from './components/Featurestwo';
import { Flex, Stack } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Turner Fenton DECA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" /> 
      </Head>

      <main>
          <Hero/>
          <Change/>


      </main>

    </div>
  )
}
