import Head from 'next/head'
import Image from 'next/image'
import { Heading, Link } from '@chakra-ui/layout';
import Portalhero from './components/Portalhero';
import Features from './components/Features';
import Exammeta from './components/Exammeta';
import Team from './components/Team';
import Change from './components/Change';
import Midpage from './components/Midpage';
import Featurestwo from './components/Featurestwo';
import { Flex, Stack } from "@chakra-ui/react";

export default function Initiatives() {
  return (
    <div>
      <Head>
      <title>Turner Fenton DECA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" /> 
      </Head>

      <main>
          <Portalhero/>
          <Exammeta/>
          <Team/>
      </main>

    </div>
  )
}
